# Generated by Django 5.0.2 on 2024-03-04 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('forename', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('department', models.CharField(choices=[('AERO', 'Aerospace Engineering'), ('BIO', 'Biomedical Engineering'), ('CPSY', 'Clinical and Applied Psychology Unit'), ('LIL', 'Department for Lifelong Learning'), ('ARC', 'Department of Archaeology'), ('ACSE', 'Department of Automatic Control and Systems Engineering'), ('CBE', 'Department of Chemical and Biological Engineering'), ('CHEM', 'Department of Chemistry'), ('CIV', 'Department of Civil and Structural Engineering'), ('COM', 'Department of Computer Science'), ('ECO', 'Department of Economics'), ('ELEC', 'Department of Electronic and Electrical Engineering'), ('GEO', 'Department of Geography'), ('LAND', 'Department of Landscape Architecture'), ('MATS', 'Department of Materials Science and Engineering'), ('MUS', 'Department of Music'), ('PHIL', 'Department of Philosophy'), ('PHYS', 'Department of Physics and Astronomy'), ('POL', 'Department of Politics and International Relations'), ('PSY', 'Department of Psychology'), ('SOC', 'Department of Sociological Studies'), ('USP', 'Department of Urban Studies and Planning'), ('GEN', 'General Engineering'), ('INF', 'Information School'), ('IWP', 'Institute of Work Psychology'), ('MNG', 'Management School'), ('MLTC', 'Modern Languages Teaching Centre'), ('AHP', 'School of Allied Health Professions'), ('ARCH', 'School of Architecture'), ('BIOS', 'School of Biosciences'), ('DEN', 'School of Clinical Dentistry'), ('EAS', 'School of East Asian Studies'), ('EDU', 'School of Education'), ('ENG', 'School of English'), ('JOU', 'School of Journalism'), ('LANG', 'School of Languages and Cultures'), ('LAW', 'School of Law'), ('MAT', 'School of Mathematics and Statistics'), ('MED', 'School of Medicine and Population Health'), ('SEFY', 'Science and Engineering Foundation Year'), ('SCIB', 'Sheffield Centre for Interdisciplinary Biblical Studies'), ('SMI', 'Sheffield Methods Institute')], max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course', models.CharField(max_length=50)),
                ('support_plan', models.FileField(blank=True, null=True, upload_to='support_plans/')),
            ],
        ),
    ]
