# Generated by Django 5.0.2 on 2024-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agendas',
            field=models.ManyToManyField(related_name='meetings', to='meetings.meetingagenda', verbose_name='MeetingAgenda'),
        ),
    ]
