# Generated by Django 5.0.2 on 2024-03-08 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECFApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='submission date')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Action Required'), (3, 'Rejected'), (4, 'Approved')], default=1, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('circumstance', models.PositiveSmallIntegerField(choices=[(1, 'Adverse Personal or Family Circumstances'), (2, 'Bereavement'), (3, 'Long Term Medical Condition'), (4, 'Short Term Medical Episode'), (5, 'Other')], verbose_name='circumstance')),
                ('description', models.TextField(verbose_name='description')),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='evidence')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ECFApplicationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Action Required'), (3, 'Rejected'), (4, 'Approved')], default=1, verbose_name='status')),
                ('module', models.CharField(max_length=15, verbose_name='module code')),
                ('assessment', models.CharField(max_length=200, verbose_name='assessment name')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Authorised Absence'), (2, 'Exam Board Consideration'), (3, 'Extension'), (4, 'Late Penalty Removal'), (5, 'Not Assessed'), (6, 'Other')], verbose_name='action')),
                ('extension_date', models.DateField(blank=True, null=True, verbose_name='extension date')),
                ('description', models.TextField(verbose_name='description')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecf_applications.ecfapplication')),
            ],
        ),
    ]
