# Generated by Django 5.0.2 on 2024-03-10 14:56

import ecf_applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfapplication',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to=ecf_applications.models.ECFApplication.gen_file_name, verbose_name='evidence'),
        ),
        migrations.AlterField(
            model_name='ecfapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Action Required'), (3, 'Under Review'), (4, 'Rejected'), (5, 'Approved')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ecfapplicationassessment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Action Required'), (3, 'Under Review'), (4, 'Rejected'), (5, 'Approved')], default=1, verbose_name='status'),
        ),
    ]
