# Generated by Django 5.0.2 on 2024-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecf_applications', '0004_alter_ecfapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfapplication',
            name='assessments',
            field=models.ManyToManyField(related_name='applications', to='ecf_applications.ecfapplicationassessment', verbose_name='ECFApplicationAssessment'),
        ),
    ]
